### ISSUE TITLE
Problem with tree_sitter_languages

### ISSUE THREAD

**Issue by gaotianyu1350** [evalplus/repoqa#49]
Hi! When I was trying to run the latest version of repoqa (0.1.2), I encountered the following problem regarding tree_sitter_languages

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/bin/repoqa.search_needle_function", line 8, in <module>
[rank0]:     sys.exit(main())
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/repoqa/search_needle_function.py", line 384, in main
[rank0]:     Fire(evaluate_model)
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/repoqa/search_needle_function.py", line 377, in evaluate_model
[rank0]:     output_json = compute_score(model, dataset, model_outputs, ignore_comments)
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/repoqa/compute_score.py", line 272, in compute_score
[rank0]:     verdict, best_target, best_similarity = needle_evaluator(
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/repoqa/compute_score.py", line 166, in needle_evaluator
[rank0]:     sanitized_output = sanitize_output(model_output, lang)
[rank0]:   File "/scratch/gpfs/tianyug/lm-training/.venv-latest-transformers-torch/lib/python3.10/site-packages/repoqa/compute_score.py", line 89, in sanitize_output
[rank0]:     parser = get_parser(lang)
[rank0]:   File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser
[rank0]:   File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
[rank0]: TypeError: __init__() takes exactly 1 argument (2 given)
```

Not sure why this happens.... The related packages (should all be up to date):

```
tree-sitter==0.22.3
tree-sitter-languages==1.10.2
```

**Comment by gaotianyu1350** [comment]
Found the problem! It seems that you need to downgrade tree-sitter to `0.21.3`!
